// @vitest-environment jsdom
/**
 * writeTerminalHistory against the real xterm: the answers it must suppress
 * are generated by xterm's own parser, so a stub could not show them.
 */
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { Terminal } from '@xterm/xterm'

vi.mock('../../rendererLogger', () => ({ rDebug: vi.fn() }))

import { writeTerminalHistory } from '../terminal-history'

const QUERIES = '\x1b]11;?\x1b\\\x1b[6n'

function openTerminal(options: { disableStdin?: boolean } = {}): { terminal: Terminal; sent: string[] } {
  const el = document.createElement('div')
  document.body.appendChild(el)
  const terminal = new Terminal({ allowTransparency: true, ...options })
  terminal.open(el)
  const sent: string[] = []
  terminal.onData((data) => sent.push(data))
  return { terminal, sent }
}

function written(terminal: Terminal, data: string): Promise<void> {
  return new Promise((resolve) => terminal.write(data, resolve))
}

beforeEach(() => {
  window.matchMedia ??= ((): MediaQueryList => ({
    matches: false, media: '', onchange: null, addListener: () => {}, removeListener: () => {},
    addEventListener: () => {}, removeEventListener: () => {}, dispatchEvent: () => false,
  })) as unknown as typeof window.matchMedia
})

describe('writeTerminalHistory', () => {
  it('answers nothing in the history and answers what is written after it', async () => {
    const { terminal, sent } = openTerminal()
    writeTerminalHistory(terminal, `prompt ${QUERIES}`, { key: 't:1' })
    await written(terminal, QUERIES)
    expect(sent).toHaveLength(2)
    expect(sent[0]).toMatch(/^\x1b\]11;rgb:/)
    expect(sent[1]).toMatch(/R$/)
    expect(terminal.options.disableStdin).toBe(false)
  })

  it('leaves a read-only terminal read-only', async () => {
    const { terminal } = openTerminal({ disableStdin: true })
    writeTerminalHistory(terminal, QUERIES, { key: 't:1' })
    await written(terminal, '')
    expect(terminal.options.disableStdin).toBe(true)
  })
})
