package ion

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
)

// parity_test.go — the structural parity guarantee.
//
// Issue #311 asks for parity to be enforced by a mechanism rather than by
// convention: "a hook or context method added to one SDK but absent from the
// other produces a test failure". This file is the Go half of that mechanism.
//
// It reads the engine's generated contract manifest and checks this SDK
// against it in both directions. A hook the engine fires with no descriptor
// here fails; a descriptor here naming a hook the engine does not fire fails;
// a payload field added on the engine side and not mirrored fails.
//
// The manifest is generated, not hand-written:
//
//	cd engine && go test ./internal/extension/ -run TestSDKContractManifest -update
//
// Reading it by relative path means this module is not testable from a bare
// checkout of sdk/go alone. That is the same trade the desktop's
// contract-sync.test.ts makes, and it is worth it: the alternative is a copy
// of the manifest that can drift from the original.

// engineManifestPath is the generated engine contract, relative to this
// package.
const engineManifestPath = "../../engine/internal/extension/testdata/sdk_contract.json"

// engineContract mirrors the manifest's on-disk shape.
type engineContract struct {
	Hooks            map[string]engineHookContract `json:"hooks"`
	ExtRequests      []string                      `json:"extRequests"`
	ExtNotifications []string                      `json:"extNotifications"`
	InitResult       []string                      `json:"initResult"`
	WireConstants    map[string]any                `json:"wireConstants"`
	ContextEnvelope  sdkJSONSchema                 `json:"contextEnvelope"`
}

type engineHookContract struct {
	PayloadKind   string   `json:"payloadKind"`
	PayloadFields []string `json:"payloadFields"`
	Result        string   `json:"result"`
	ResultFields  []string `json:"resultFields"`
}

// sdkJSONSchema mirrors the recursive `_ctx` shape generated by the engine.
type sdkJSONSchema struct {
	Kind   string                   `json:"kind"`
	Fields map[string]sdkJSONSchema `json:"fields"`
}

func loadEngineContract(t *testing.T) engineContract {
	t.Helper()
	data, err := os.ReadFile(filepath.Clean(engineManifestPath))
	if err != nil {
		t.Fatalf("read engine contract manifest at %s: %v\n"+
			"This module's parity tests read the engine's generated manifest, so they run "+
			"from a full Ion checkout. Regenerate it with:\n"+
			"  cd engine && go test ./internal/extension/ -run TestSDKContractManifest -update",
			engineManifestPath, err)
	}
	var contract engineContract
	if err := json.Unmarshal(data, &contract); err != nil {
		t.Fatalf("decode engine contract manifest: %v", err)
	}
	if len(contract.Hooks) == 0 {
		t.Fatal("engine contract manifest has no hooks; it is empty or malformed")
	}
	return contract
}

// TestSDKParityWithEngineManifest is the bidirectional hook check.
func TestSDKParityWithEngineManifest(t *testing.T) {
	contract := loadEngineContract(t)

	descriptors := map[string]descriptorInfo{}
	for _, d := range allHookDescriptors() {
		if prev, dup := descriptors[d.Name]; dup {
			t.Errorf("hook %q has two descriptors (%v and %v)", d.Name, prev.Payload, d.Payload)
		}
		descriptors[d.Name] = d
	}

	// Direction one: every engine hook has a descriptor.
	var missing []string
	for name := range contract.Hooks {
		if _, ok := descriptors[name]; !ok {
			missing = append(missing, name)
		}
	}
	sort.Strings(missing)
	if len(missing) > 0 {
		t.Errorf("engine hooks with no Go SDK descriptor: %v\n"+
			"Add a Hook[P, R] to hook_descriptors.go (and its payload struct to "+
			"hook_payloads.go) and list it in allHookDescriptors().", missing)
	}

	// Direction two: no descriptor names a hook the engine does not fire.
	var extra []string
	for name := range descriptors {
		if _, ok := contract.Hooks[name]; !ok {
			extra = append(extra, name)
		}
	}
	sort.Strings(extra)
	if len(extra) > 0 {
		t.Errorf("Go SDK descriptors for hooks the engine does not declare: %v\n"+
			"Either the hook was removed from the engine (delete the descriptor) or the "+
			"name is misspelled.", extra)
	}

	// Payload shapes must match field for field.
	for name, spec := range contract.Hooks {
		desc, ok := descriptors[name]
		if !ok {
			continue // already reported above
		}
		checkPayloadParity(t, name, spec, desc)
	}
}

// checkPayloadParity compares one hook's declared payload against the Go
// descriptor's payload type.
func checkPayloadParity(t *testing.T, name string, spec engineHookContract, desc descriptorInfo) {
	t.Helper()

	switch spec.PayloadKind {
	case "none":
		// The engine sends no payload. A descriptor may use NoPayload, or a
		// raw message for hooks whose payload the engine does not model as a
		// struct (the per-tool hooks send the tool's own argument object).
		return

	case "string":
		if desc.Payload == nil || desc.Payload.Kind() != reflect.String {
			t.Errorf("hook %q: engine sends a bare string, Go descriptor payload is %v",
				name, desc.Payload)
		}
		return

	case "object":
		if desc.Payload == nil {
			t.Errorf("hook %q: engine sends an object payload but the descriptor has none", name)
			return
		}
		// A raw-message payload is a deliberate pass-through for shapes the
		// engine itself does not fix (tool arguments, tool results). Nothing
		// to compare field-wise.
		if isRawMessageType(desc.Payload) {
			return
		}
		if desc.Payload.Kind() != reflect.Struct {
			t.Errorf("hook %q: engine sends an object, Go descriptor payload is %v",
				name, desc.Payload)
			return
		}
		want := spec.PayloadFields
		got := jsonFieldNamesOf(desc.Payload)
		if !equalStrings(want, got) {
			t.Errorf("hook %q payload fields differ:\n  engine: %v\n  go sdk: %v\n"+
				"Update %s in hook_payloads.go to mirror the engine struct, then re-run.",
				name, want, got, desc.Payload.Name())
		}

	default:
		t.Errorf("hook %q: manifest declares unknown payloadKind %q", name, spec.PayloadKind)
	}
}

// TestResultParityWithEngineManifest checks the structured result shapes. The
// engine reads specific fields off a structured result, so a mismatch here
// means a handler's decision is silently discarded rather than rejected.
func TestResultParityWithEngineManifest(t *testing.T) {
	contract := loadEngineContract(t)

	descriptors := map[string]descriptorInfo{}
	for _, d := range allHookDescriptors() {
		descriptors[d.Name] = d
	}

	for name, spec := range contract.Hooks {
		desc, ok := descriptors[name]
		if !ok {
			continue
		}
		if spec.Result != "structured" {
			continue
		}
		if desc.Result == nil || desc.Result.Kind() != reflect.Struct {
			t.Errorf("hook %q declares a structured result but the Go descriptor's result is %v",
				name, desc.Result)
			continue
		}
		want := spec.ResultFields
		got := jsonFieldNamesOf(desc.Result)
		if !equalStrings(want, got) {
			t.Errorf("hook %q result fields differ:\n  engine: %v\n  go sdk: %v",
				name, want, got)
		}
	}
}

// TestResultCategoryParity pins each hook's result category to a Go result
// type. Without it a hook could carry a plausible payload and a result type
// the engine will never read — an abstention that looks like an opinion.
func TestResultCategoryParity(t *testing.T) {
	contract := loadEngineContract(t)

	descriptors := map[string]descriptorInfo{}
	for _, d := range allHookDescriptors() {
		descriptors[d.Name] = d
	}

	// The Go result type each engine result category maps to.
	expected := map[string]func(reflect.Type) bool{
		"none":   func(rt reflect.Type) bool { return rt == reflect.TypeOf(NoResult{}) },
		"string": func(rt reflect.Type) bool { return rt == reflect.TypeOf(StringResult("")) },
		"bool":   func(rt reflect.Type) bool { return rt == reflect.TypeOf(BoolResult(false)) },
		"block":  func(rt reflect.Type) bool { return rt == reflect.TypeOf(ToolCallResult{}) },
		"perToolCall": func(rt reflect.Type) bool {
			return rt == reflect.TypeOf(PerToolCallResult{})
		},
		"rejection": func(rt reflect.Type) bool {
			return rt == reflect.TypeOf(ContextRejectionResult{})
		},
		"content":   isRawMessageType,
		"asyncVeto": func(rt reflect.Type) bool { return rt == reflect.TypeOf(AsyncRegistrationVeto{}) },
		"structured": func(rt reflect.Type) bool {
			return rt != nil && rt.Kind() == reflect.Struct
		},
	}

	for name, spec := range contract.Hooks {
		desc, ok := descriptors[name]
		if !ok {
			continue
		}
		check, known := expected[spec.Result]
		if !known {
			t.Errorf("hook %q: manifest declares unknown result category %q", name, spec.Result)
			continue
		}
		if desc.Result == nil || !check(desc.Result) {
			t.Errorf("hook %q: engine result category %q, Go descriptor result type %v",
				name, spec.Result, desc.Result)
		}
	}
}

// TestWireConstantsMatchEngine pins the three framing values. Each is a silent
// failure if it drifts: a wrong id base misroutes responses, a wrong wrapper
// key hands handlers the envelope instead of the payload, and a wrong ctx key
// leaves metadata in the payload.
func TestWireConstantsMatchEngine(t *testing.T) {
	contract := loadEngineContract(t)

	base, ok := contract.WireConstants["extRequestIdBase"].(float64)
	if !ok {
		t.Fatalf("manifest wireConstants.extRequestIdBase is not a number: %v",
			contract.WireConstants["extRequestIdBase"])
	}
	if int64(base) != extRequestIDBase {
		t.Errorf("extRequestIdBase: engine %d, Go SDK %d", int64(base), extRequestIDBase)
	}

	if got := contract.WireConstants["payloadWrapperKey"]; got != payloadWrapperKey {
		t.Errorf("payloadWrapperKey: engine %v, Go SDK %q", got, payloadWrapperKey)
	}
	if got := contract.WireConstants["ctxKey"]; got != ctxKey {
		t.Errorf("ctxKey: engine %v, Go SDK %q", got, ctxKey)
	}
}

func TestContextEnvelopeMatchesEngineManifest(t *testing.T) {
	contract := loadEngineContract(t)
	if contract.ContextEnvelope.Kind != "object" {
		t.Fatalf("engine contextEnvelope kind = %q, want object", contract.ContextEnvelope.Kind)
	}
	if err := compareContextSchema(contract.ContextEnvelope, reflect.TypeOf(ctxEnvelope{}), "_ctx"); err != nil {
		t.Error(err)
	}
}

func compareContextSchema(want sdkJSONSchema, got reflect.Type, path string) error {
	for got.Kind() == reflect.Ptr {
		got = got.Elem()
	}
	if got.Kind() != reflect.Struct {
		return fmt.Errorf("%s: Go SDK type is %s, engine requires %s", path, got, want.Kind)
	}

	fields := map[string]reflect.Type{}
	for i := range got.NumField() {
		field := got.Field(i)
		tag := strings.Split(field.Tag.Get("json"), ",")[0]
		if tag == "" || tag == "-" {
			continue
		}
		fields[tag] = field.Type
	}
	for name, wantField := range want.Fields {
		gotField, ok := fields[name]
		if !ok {
			return fmt.Errorf("%s.%s: Go SDK is missing engine envelope field", path, name)
		}
		if err := compareContextFieldSchema(wantField, gotField, path+"."+name); err != nil {
			return err
		}
		delete(fields, name)
	}
	for name := range fields {
		return fmt.Errorf("%s.%s: Go SDK envelope field is not emitted by engine", path, name)
	}
	return nil
}

func compareContextFieldSchema(want sdkJSONSchema, got reflect.Type, path string) error {
	for got.Kind() == reflect.Ptr {
		got = got.Elem()
	}
	switch want.Kind {
	case "string":
		if got.Kind() != reflect.String {
			return fmt.Errorf("%s: Go SDK kind %s, engine kind string", path, got.Kind())
		}
	case "number":
		if got.Kind() < reflect.Int || got.Kind() > reflect.Float64 {
			return fmt.Errorf("%s: Go SDK kind %s, engine kind number", path, got.Kind())
		}
	case "boolean":
		if got.Kind() != reflect.Bool {
			return fmt.Errorf("%s: Go SDK kind %s, engine kind boolean", path, got.Kind())
		}
	case "object":
		return compareContextSchema(want, got, path)
	default:
		return fmt.Errorf("%s: engine schema declares unknown kind %q", path, want.Kind)
	}
	return nil
}

// TestInitResultFieldsMatchEngine pins the handshake shape. A field the engine
// reads but the SDK never sends is a registration that silently disappears.
func TestInitResultFieldsMatchEngine(t *testing.T) {
	contract := loadEngineContract(t)

	got := jsonFieldNamesOf(reflect.TypeOf(initResult{}))
	want := append([]string{}, contract.InitResult...)
	sort.Strings(want)

	if !equalStrings(want, got) {
		t.Errorf("init result fields differ:\n  engine reads: %v\n  go sdk sends: %v\n"+
			"Update initResult in dispatch.go.", want, got)
	}
}

// TestExtMethodsAreClaimed applies the structure-not-convention rule to the
// SDK itself: every ext/* method the engine answers must be named by exactly
// one entry in the SDK's own declared method registry.
//
// Without this, the SDK could quietly omit a capability the engine offers and
// nothing would notice — which is the same class of drift the whole manifest
// exists to prevent, just pointed the other way.
func TestExtMethodsAreClaimed(t *testing.T) {
	contract := loadEngineContract(t)
	claimed := sdkClaimedMethods()

	var unclaimed []string
	for _, method := range contract.ExtRequests {
		if _, ok := claimed[method]; !ok {
			unclaimed = append(unclaimed, method)
		}
	}
	sort.Strings(unclaimed)
	if len(unclaimed) > 0 {
		t.Errorf("engine ext/* request methods this SDK does not implement: %v\n"+
			"Add the method to the SDK and register it in sdkClaimedMethods() "+
			"(methods.go), naming the Go function that issues it.", unclaimed)
	}

	var phantom []string
	for method := range claimed {
		if !containsString(contract.ExtRequests, method) &&
			!containsString(contract.ExtNotifications, method) {
			phantom = append(phantom, method)
		}
	}
	sort.Strings(phantom)
	if len(phantom) > 0 {
		t.Errorf("SDK claims ext/* methods the engine does not answer: %v\n"+
			"These calls would return -32601 at runtime.", phantom)
	}
}

// TestNotificationMethodsAreClaimed is the notification half of the same
// check.
func TestNotificationMethodsAreClaimed(t *testing.T) {
	contract := loadEngineContract(t)
	claimed := sdkClaimedMethods()

	var unclaimed []string
	for _, method := range contract.ExtNotifications {
		if _, ok := claimed[method]; !ok {
			unclaimed = append(unclaimed, method)
		}
	}
	sort.Strings(unclaimed)
	if len(unclaimed) > 0 {
		t.Errorf("engine notification methods this SDK never sends: %v", unclaimed)
	}
}

// TestDescriptorTableIsComplete guards allHookDescriptors() against a
// descriptor declared in hook_descriptors.go but left out of the table. Such a
// descriptor would be usable but invisible to every parity check above, which
// is worse than not having it.
func TestDescriptorTableIsComplete(t *testing.T) {
	src, err := os.ReadFile("hook_descriptors.go")
	if err != nil {
		t.Fatalf("read hook_descriptors.go: %v", err)
	}
	body := string(src)

	listed := map[string]bool{}
	for _, d := range allHookDescriptors() {
		listed[d.Name] = true
	}

	// Each descriptor is declared as `var HookX = Hook[...]{Name: HookNameX}`.
	// Count the declarations and compare with the table's length: a name-level
	// comparison is not possible without evaluating the constants, but a count
	// mismatch catches the omission this test exists for.
	declared := strings.Count(body, "= Hook[")
	if declared != len(listed) {
		t.Errorf("hook_descriptors.go declares %d descriptors but allHookDescriptors() lists %d.\n"+
			"Every `var HookX = Hook[...]` must appear in allHookDescriptors(), or the parity "+
			"tests cannot see it.", declared, len(listed))
	}
}

// --- helpers ---

func isRawMessageType(rt reflect.Type) bool {
	if rt == nil {
		return false
	}
	if rt == reflect.TypeOf(json.RawMessage{}) {
		return true
	}
	// ToolInput and ToolResultInfo are named json.RawMessage types.
	return rt.Kind() == reflect.Slice && rt.Elem().Kind() == reflect.Uint8
}

// jsonFieldNamesOf returns a struct's sorted JSON field names, matching the
// engine generator's extraction so the two lists are comparable.
func jsonFieldNamesOf(rt reflect.Type) []string {
	for rt != nil && rt.Kind() == reflect.Ptr {
		rt = rt.Elem()
	}
	if rt == nil || rt.Kind() != reflect.Struct {
		return nil
	}
	var names []string
	for i := range rt.NumField() {
		f := rt.Field(i)
		tag := f.Tag.Get("json")
		if tag == "" || tag == "-" {
			continue
		}
		name := strings.Split(tag, ",")[0]
		if name == "" {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func containsString(haystack []string, needle string) bool {
	for _, s := range haystack {
		if s == needle {
			return true
		}
	}
	return false
}
