<#
.SYNOPSIS
  Applies the Ion Engine machine policy and the theme pack it locks.

.DESCRIPTION
  The install command of the Ion Enterprise Policy Win32 app. It reads
  IonPolicy.json from beside itself and places two things:

    - exactly the declared values under HKLM\SOFTWARE\Policies\IonEngine,
      the only registry location the engine reads policy from;
    - the declared theme pack under %ProgramData%\Ion\themes\<id>, the
      machine-scope pack root the desktop scans
      (desktop/src/main/theme-packs.ts).

  The theme travels with the policy because the policy LOCKS it. A device that
  applied a locked themePolicy without the pack would fall back to a built-in
  theme and report itself compliant, so the two are one unit or the device is
  compliant and wrong.

  Four properties this script exists to guarantee:

  1. It writes exactly what the package declares, and nothing else. The
     package is generated by New-IonPolicyPackage.ps1, which validates every
     input before a package exists at all.

  2. It VERIFIES what it wrote. A New-ItemProperty that appeared to succeed
     and a policy key that actually carries the value are different facts,
     and on a managed fleet the difference is a device that reports compliant
     while running unmanaged. Every value is read back and compared, and every
     theme file's SHA-256 is compared against the payload; a mismatch fails
     the install so Intune retries and reports it.

  3. The theme lands ATOMICALLY, and the theme and the policy land TOGETHER.
     Files are staged in a sibling directory and hashed there, and only a
     directory swap makes them live -- so a failure part-way leaves the
     previous pack exactly as it was rather than a half-written one the
     desktop would load. An update replaces the files this package owns; a
     pack directory some other tool placed under a different id is never
     touched. The swap opens a transaction that closes only when every policy
     value has been written, read back and recorded as owned: the previous
     pack is retained until then, and a failure anywhere in the policy phase
     removes the new pack, restores the previous one, and puts the registry
     back to the state it was in before the run. A device therefore never
     carries this package's theme with somebody else's policy, and never
     carries half an ownership record for the next uninstall to act on.

  4. It records what it owns. The owned value names and the owned theme
     directory go to HKLM\SOFTWARE\Ion\PolicyPackage -- a key the engine never
     reads -- so uninstall can remove this package's configuration and leave
     anything an administrator set by hand, delivered by Group Policy, or
     installed as a different theme exactly where it is. Re-running with a
     newer package converges: values this package no longer declares are
     removed, the rest are overwritten.

  Runs as SYSTEM (Intune "Install behavior: System"). It writes HKLM and one
  directory under %ProgramData%\Ion\themes. It never touches a user profile,
  %USERPROFILE%\.ion, conversations, credentials, an operator's ~\orion or
  ~\.orion, another theme pack, or the administrator-authored
  enterprise-config files under %ProgramData%\Ion.

.PARAMETER PolicyFile
  Overrides the payload path. For a manual run; Intune runs this with no
  arguments.

.PARAMETER WhatIfOnly
  Print what would be written and exit without touching the registry or disk.
#>
[CmdletBinding()]
param(
  [string] $PolicyFile,
  [switch] $WhatIfOnly
)

$ErrorActionPreference = 'Stop'

# The engine's policy key. Not configurable: it is the engine's contract, and
# a package that wrote somewhere else would apply nothing while reporting
# success. See engine/internal/config/enterprise_windows.go.
$PolicyKey = 'HKLM:\SOFTWARE\Policies\IonEngine'
# Where this package records what it owns. Deliberately NOT under the policy
# key: the engine enumerates every value there and would report an ownership
# record as unknown policy.
$OwnershipKey = 'HKLM:\SOFTWARE\Ion\PolicyPackage'

if (-not $PolicyFile) { $PolicyFile = Join-Path $PSScriptRoot 'IonPolicy.json' }

function Write-IonPolicyLog([string] $Message) {
  Write-Output "Install-IonPolicy: $Message"
}

if (-not (Test-Path -LiteralPath $PolicyFile)) {
  [Console]::Error.WriteLine("Install-IonPolicy: payload not found at $PolicyFile")
  exit 1
}

try {
  $payload = Get-Content -LiteralPath $PolicyFile -Raw | ConvertFrom-Json
} catch {
  [Console]::Error.WriteLine("Install-IonPolicy: $PolicyFile is not valid JSON: $($_.Exception.Message)")
  exit 1
}

if ($payload.schema -ne 2) {
  [Console]::Error.WriteLine("Install-IonPolicy: unsupported payload schema '$($payload.schema)'. This installer understands schema 2.")
  exit 1
}
if (-not $payload.packageVersion) {
  [Console]::Error.WriteLine('Install-IonPolicy: the payload carries no packageVersion, so detection and rollback could not identify it.')
  exit 1
}
if (-not $payload.values -or @($payload.values).Count -eq 0) {
  [Console]::Error.WriteLine('Install-IonPolicy: the payload declares no values. A package that applies nothing is a packaging error, not an empty policy.')
  exit 1
}
if (-not $payload.theme -or -not $payload.theme.id -or @($payload.theme.files).Count -eq 0) {
  [Console]::Error.WriteLine('Install-IonPolicy: the payload carries no theme pack. The policy locks a theme, so a package without one produces a device that renders a built-in theme and reports compliant.')
  exit 1
}

# An API key is a per-user secret. It has no business in a machine policy that
# every account on the device can read, and the packaging tool refuses to put
# one there -- this is the second gate, on the device, in case a payload was
# hand-edited after packaging.
$payloadText = Get-Content -LiteralPath $PolicyFile -Raw
if ($payloadText -match '"apiKey"') {
  [Console]::Error.WriteLine('Install-IonPolicy: the payload contains an apiKey. Machine policy is world-readable; refusing to write a credential to it.')
  exit 1
}

$themeId = [string] $payload.theme.id
if ($themeId -notmatch '^[a-z0-9][a-z0-9-]{0,63}$') {
  [Console]::Error.WriteLine("Install-IonPolicy: the payload's theme id '$themeId' is not a usable pack directory name.")
  exit 1
}
$themesRoot = Join-Path ([Environment]::GetEnvironmentVariable('ProgramData')) 'Ion\themes'
$packDir = Join-Path $themesRoot $themeId
$stagingDir = Join-Path $themesRoot ".$themeId.staging"
$retiredDir = Join-Path $themesRoot ".$themeId.retired"
$themeSource = Join-Path $PSScriptRoot 'theme'

Write-IonPolicyLog "package version $($payload.packageVersion), $(@($payload.values).Count) value(s) -> $PolicyKey"
foreach ($v in $payload.values) {
  $rendered = if ($v.value -is [array]) { ($v.value -join ' | ') } else { [string] $v.value }
  if ($rendered.Length -gt 200) { $rendered = $rendered.Substring(0, 200) + '...' }
  Write-IonPolicyLog "  $($v.name) [$($v.type)] = $rendered"
}
Write-IonPolicyLog "theme $themeId $($payload.theme.version), $(@($payload.theme.files).Count) file(s) -> $packDir"

if ($WhatIfOnly) {
  Write-IonPolicyLog '-WhatIfOnly given, nothing was modified'
  exit 0
}

# ── The theme pack, staged and verified before anything goes live ────────────

if (-not (Test-Path -LiteralPath $themesRoot)) {
  New-Item -ItemType Directory -Path $themesRoot -Force | Out-Null
  Write-IonPolicyLog "created $themesRoot"
}
if (Test-Path -LiteralPath $stagingDir) { Remove-Item -LiteralPath $stagingDir -Recurse -Force }
New-Item -ItemType Directory -Path $stagingDir -Force | Out-Null

$ownedThemeFiles = @()
try {
  foreach ($f in @($payload.theme.files)) {
    $rel = [string] $f.path
    $src = Join-Path $themeSource ($rel -replace '/', '\')
    if (-not (Test-Path -LiteralPath $src)) {
      throw "the payload declares theme file '$rel' but the package does not carry it."
    }
    $dest = Join-Path $stagingDir ($rel -replace '/', '\')
    $destDir = Split-Path -Parent $dest
    if (-not (Test-Path -LiteralPath $destDir)) { New-Item -ItemType Directory -Path $destDir -Force | Out-Null }
    Copy-Item -LiteralPath $src -Destination $dest -Force
    $actual = (Get-FileHash -LiteralPath $dest -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($actual -ne ([string] $f.sha256).ToLowerInvariant()) {
      throw "theme file '$rel' hashes to $actual but the payload declares $($f.sha256). The package is damaged or was edited after packaging."
    }
    $ownedThemeFiles += "$rel $actual"
  }
} catch {
  Remove-Item -LiteralPath $stagingDir -Recurse -Force -ErrorAction SilentlyContinue
  [Console]::Error.WriteLine("Install-IonPolicy: $($_.Exception.Message)")
  exit 1
}
Write-IonPolicyLog "staged and hash-verified $($ownedThemeFiles.Count) theme file(s)"

# ── The registry state this run is about to replace ──────────────────────────
# Captured BEFORE anything goes live, because the theme swap and the policy
# write are one transaction. A device that ends up carrying this package's
# theme while the policy write failed is a device that renders the managed
# brand and is configured by something else, and a half-written ownership
# record is one the next uninstall would act on. So: snapshot, swap, write,
# and undo all of it together if any part of it fails.

$policyKeyExisted = Test-Path -LiteralPath $PolicyKey
$ownershipKeyExisted = Test-Path -LiteralPath $OwnershipKey

function Get-IonRegistrySnapshot([string] $Path) {
  # name -> @{ Value; Kind }. A name that is absent is simply not in the map,
  # which is what tells the restore to remove it rather than put it back.
  $snapshot = @{}
  if (-not (Test-Path -LiteralPath $Path)) { return $snapshot }
  $snapKey = Get-Item -LiteralPath $Path
  foreach ($name in @($snapKey.GetValueNames() | Where-Object { $_ -ne '' })) {
    $snapshot[$name] = @{
      Value = $snapKey.GetValue($name, $null, [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
      Kind  = [string] $snapKey.GetValueKind($name)
    }
  }
  return $snapshot
}

function Restore-IonRegistrySnapshot([string] $Path, [hashtable] $Snapshot, [bool] $KeyExisted) {
  # Best effort by construction: this runs on a path where something already
  # failed, and a rollback that threw would leave more behind than it removed.
  if (-not $KeyExisted) {
    Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction SilentlyContinue
    return
  }
  if (-not (Test-Path -LiteralPath $Path)) { New-Item -Path $Path -Force -ErrorAction SilentlyContinue | Out-Null }
  if (-not (Test-Path -LiteralPath $Path)) { return }
  $liveKey = Get-Item -LiteralPath $Path
  foreach ($name in @($liveKey.GetValueNames() | Where-Object { $_ -ne '' })) {
    if (-not $Snapshot.ContainsKey($name)) {
      Remove-ItemProperty -LiteralPath $Path -Name $name -Force -ErrorAction SilentlyContinue
    }
  }
  foreach ($name in @($Snapshot.Keys)) {
    New-ItemProperty -LiteralPath $Path -Name $name -PropertyType $Snapshot[$name].Kind `
      -Value $Snapshot[$name].Value -Force -ErrorAction SilentlyContinue | Out-Null
  }
}

$policySnapshot = Get-IonRegistrySnapshot $PolicyKey
$ownershipSnapshot = Get-IonRegistrySnapshot $OwnershipKey

# The swap. Two renames rather than a copy over the live directory, so the
# desktop never observes a half-written pack: the pack is either the previous
# one or this one, and the window between them is a rename.
if (Test-Path -LiteralPath $retiredDir) { Remove-Item -LiteralPath $retiredDir -Recurse -Force }
$hadPrevious = Test-Path -LiteralPath $packDir
try {
  if ($hadPrevious) { Move-Item -LiteralPath $packDir -Destination $retiredDir -Force }
  Move-Item -LiteralPath $stagingDir -Destination $packDir -Force
} catch {
  # Put the previous pack back. A device left with no theme at all is worse
  # than one still carrying the version it had before this attempt.
  if ($hadPrevious -and -not (Test-Path -LiteralPath $packDir) -and (Test-Path -LiteralPath $retiredDir)) {
    Move-Item -LiteralPath $retiredDir -Destination $packDir -Force
    Write-IonPolicyLog 'the swap failed; the previous theme pack was restored'
  }
  Remove-Item -LiteralPath $stagingDir -Recurse -Force -ErrorAction SilentlyContinue
  [Console]::Error.WriteLine("Install-IonPolicy: could not install the theme pack: $($_.Exception.Message)")
  exit 1
}
# The retired pack STAYS until the policy phase below has fully succeeded. It
# is the only copy of what this device had, and it is what the rollback puts
# back if a policy write, a readback or the ownership record fails.
Write-IonPolicyLog $(if ($hadPrevious) { "replaced the theme pack at $packDir" } else { "installed the theme pack at $packDir" })

# ── The policy values, inside the transaction the swap opened ────────────────
# Everything from here to the last ownership value either all lands or none of
# it does. A failure anywhere below restores the registry to the snapshot taken
# before the swap, removes the pack this run installed, and puts the retired
# pack back -- so a failed install leaves the device exactly as the last
# successful one left it, and Intune retries against a known state.

$declared = @($payload.values | ForEach-Object { $_.name })
try {
  foreach ($key in @($PolicyKey, $OwnershipKey)) {
    if (-not (Test-Path -LiteralPath $key)) {
      New-Item -Path $key -Force | Out-Null
      Write-IonPolicyLog "created $key"
    }
  }

  # Values this package owned before this run. Anything it owned and no longer
  # declares is removed, so an update that drops a setting actually drops it
  # rather than leaving the old value enforced forever.
  $previouslyOwned = @()
  $existing = Get-ItemProperty -LiteralPath $OwnershipKey -ErrorAction SilentlyContinue
  if ($existing -and $existing.OwnedValues) { $previouslyOwned = @($existing.OwnedValues) }

  foreach ($stale in ($previouslyOwned | Where-Object { $declared -notcontains $_ })) {
    Remove-ItemProperty -LiteralPath $PolicyKey -Name $stale -Force -ErrorAction SilentlyContinue
    Write-IonPolicyLog "removed $stale, which this package no longer declares"
  }

  foreach ($v in $payload.values) {
    New-ItemProperty -LiteralPath $PolicyKey -Name $v.name -PropertyType $v.type -Value $v.value -Force | Out-Null
  }

  # Verify. A write that reported success and a key that carries the value are
  # different facts, and only the second one manages a device. The registry KIND
  # is checked too: a REG_SZ where the payload declares a REG_MULTI_SZ decodes
  # differently in the engine, so equal text is not enough.
  $key = Get-Item -LiteralPath $PolicyKey
  $mismatches = @()
  foreach ($v in $payload.values) {
    $actual = $key.GetValue($v.name, $null, [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
    $kind = [string] $key.GetValueKind($v.name)
    $ok = $kind -eq [string] $v.type
    if ($ok) {
      $ok = if ($v.value -is [array]) {
        (@($actual) -join "`u{1}") -eq (@($v.value) -join "`u{1}")
      } else {
        [string] $actual -eq [string] $v.value
      }
    }
    if (-not $ok) { $mismatches += "$($v.name) (kind $kind)" }
  }
  if ($mismatches.Count -gt 0) {
    throw "wrote $($mismatches -join ', ') but read back a different value. The policy was NOT applied correctly."
  }
  Write-IonPolicyLog "verified $(@($payload.values).Count) value(s) read back exactly as written"

  New-ItemProperty -LiteralPath $OwnershipKey -Name 'Version' -PropertyType String -Value ([string] $payload.packageVersion) -Force | Out-Null
  New-ItemProperty -LiteralPath $OwnershipKey -Name 'OwnedValues' -PropertyType MultiString -Value $declared -Force | Out-Null
  New-ItemProperty -LiteralPath $OwnershipKey -Name 'ThemeId' -PropertyType String -Value $themeId -Force | Out-Null
  New-ItemProperty -LiteralPath $OwnershipKey -Name 'ThemeVersion' -PropertyType String -Value ([string] $payload.theme.version) -Force | Out-Null
  New-ItemProperty -LiteralPath $OwnershipKey -Name 'ThemePath' -PropertyType String -Value $packDir -Force | Out-Null
  New-ItemProperty -LiteralPath $OwnershipKey -Name 'ThemeFiles' -PropertyType MultiString -Value $ownedThemeFiles -Force | Out-Null
  New-ItemProperty -LiteralPath $OwnershipKey -Name 'InstalledAtUtc' -PropertyType String -Value ((Get-Date).ToUniversalTime().ToString('o')) -Force | Out-Null
} catch {
  $reason = $_.Exception.Message
  Restore-IonRegistrySnapshot $PolicyKey $policySnapshot $policyKeyExisted
  Restore-IonRegistrySnapshot $OwnershipKey $ownershipSnapshot $ownershipKeyExisted
  Remove-Item -LiteralPath $packDir -Recurse -Force -ErrorAction SilentlyContinue
  if ($hadPrevious -and -not (Test-Path -LiteralPath $packDir) -and (Test-Path -LiteralPath $retiredDir)) {
    Move-Item -LiteralPath $retiredDir -Destination $packDir -Force -ErrorAction SilentlyContinue
  }
  Remove-Item -LiteralPath $retiredDir -Recurse -Force -ErrorAction SilentlyContinue
  Write-IonPolicyLog $(if ($hadPrevious) {
    'the policy phase failed; the theme pack was rolled back to the previous one and the registry was restored'
  } else {
    'the policy phase failed; the theme pack this run installed was removed and the registry was restored'
  })
  [Console]::Error.WriteLine("Install-IonPolicy: $reason")
  exit 1
}

# The install is complete, so the previous pack is finally disposable. Deleting
# it any earlier would leave a failed install with no pack to go back to.
Remove-Item -LiteralPath $retiredDir -Recurse -Force -ErrorAction SilentlyContinue

Write-IonPolicyLog "recorded ownership of $($declared.Count) value(s) and theme $themeId at $OwnershipKey"
Write-IonPolicyLog 'restart the Ion Engine scheduled task for the change to take effect'
exit 0
