/**
 * TS-side field maps for the cross-language contract-sync tests.
 *
 * Split out of contract-sync.test.ts to keep that file under the 600-line
 * cap. These are pure data (not tests); contract-sync.test.ts imports and
 * validates them against the Go-generated manifest.
 *
 * When you update a TS type, update the corresponding map here in the same PR.
 * If you forget, CI fails.
 */

// ─── TS NormalizedEvent field map ───
// Each key is the `type` discriminator; each value is the list of non-type
// fields for that variant. Keep sorted to match the Go manifest.

export const TS_NORMALIZED_EVENTS: Record<string, string[]> = {
  background_work_delivered: ["content", "entryId", "work"],
  session_init: [
    "isWarmup",
    "mcpServers",
    "model",
    "sessionId",
    "skills",
    "tools",
    "version",
  ],
  text_chunk: ["text"],
  tool_call: ["index", "toolId", "toolName"],
  tool_call_update: ["partialInput", "toolId"],
  tool_call_complete: ["index"],
  tool_result: ["backgroundTaskId", "content", "images", "isError", "toolId"],
  task_update: ["message"],
  task_complete: [
    "conversationTurns",
    "costUsd",
    "durationMs",
    "lastText",
    "numTurns",
    "permissionDenials",
    "reason",
    "result",
    "sessionId",
    "usage",
  ],
  error: [
    "contextLimit",
    "contextTokens",
    "contextWindow",
    "errorCode",
    "httpStatus",
    "isError",
    "message",
    "retryAfterMs",
    "retryable",
    "sessionId",
    "stderrTail",
  ],
  session_dead: ["exitCode", "signal", "stderrTail"],
  rate_limit: ["rateLimitType", "resetsAt", "status"],
  usage: ["entryId", "usage", "userEntryId"],
  permission_request: [
    "options",
    "questionId",
    "toolDescription",
    "toolInput",
    "toolName",
  ],
  plan_mode_changed: ["enabled", "planFilePath", "planSlug"],
  plan_file_written: ["operation", "planFilePath", "planSlug"],
  plan_proposal: ["kind", "planFilePath", "planSlug"],
  plan_mode_auto_exit: [
    "planFilePath",
    "planSlug",
    "reason",
    "runId",
    "sessionId",
    "stopReason",
  ],
  stream_reset: [],
  compacting: [
    "active",
    "clearedBlocks",
    "messagesAfter",
    "messagesBefore",
    "microOnly",
    "strategy",
    "summary",
  ],
  tool_stalled: ["elapsed", "toolId", "toolName"],
  steer_injected: [
    "clientMessageId",
    "entryId",
    "kind",
    "machineAuthored",
    "messageLength",
  ],
  steer_degraded: ["messageLength"],
  agent_state_clamped: [
    "agentName",
    "scope",
    "clampedKeys",
    "droppedKeys",
    "originalBytes",
    "clampedBytes",
    "limitBytes",
  ],
  prompt_injected: ["kind", "machineAuthored", "origin", "prompt"],
  run_recovery: ["attempt", "maxAttempts", "phase", "reason", "recoveryId"],
  model_fallback: ["fallbackModel", "reason", "requestedModel"],
  capability_unsupported: ["backend", "capability", "reason"],
  run_stalled: ["lastActivity", "stalledDuration"],
  task_suspend: ["awaitingDispatchIds", "awaitingTaskIds"],
  background_task_started: [
    "command",
    "notifyOnComplete",
    "startedAt",
    "taskId",
  ],
  background_task_terminal: [
    "command",
    "elapsedMs",
    "exitCode",
    "outputPath",
    "status",
    "tail",
    "taskId",
  ],
  session_work_stopped: [
    "cancelledRunId",
    "killedAgentProcessCount",
    "recalledDispatchIds",
    "scope",
    "stoppedBackgroundTaskIds",
  ],
  background_task_complete: [
    "command",
    "elapsedMs",
    "exitCode",
    "outputPath",
    "remainingTaskIds",
    "status",
    "tail",
    "taskId",
  ],
  engine_plan_content: [
    "content",
    "hasMore",
    "offset",
    "planFilePath",
    "totalBytes",
  ],
  thinking_block_start: [],
  thinking_delta: ["text"],
  thinking_block_end: ["elapsedSeconds", "redacted", "totalTokens"],
  // Extension-surface events (WI-001: single-path collapse)
  message_end: [
    "contextPercent",
    "cost",
    "entryId",
    "inputTokens",
    "outputTokens",
    "userEntryId",
  ],
  user_turn_persisted: [
    "entryId",
    "slashFrontmatter",
    "slashModelAlias",
    "slashModelEffective",
  ],
  agent_state: ["agents"],
  harness_message: ["dedupKey", "dedupMode", "message", "source"],
  working_message: ["message"],
  notify: ["level", "message"],
  dialog: ["defaultValue", "dialogId", "method", "options", "title"],
  extension_died: ["extensionName"],
  extension_respawned: ["attemptNumber", "extensionName"],
  extension_dead_permanent: ["attemptNumber", "extensionName"],
  events_dropped: ["count"],
  image_content: ["contentHash", "mediaType", "path", "source", "toolId"],
  // Per-category token breakdown. Emitted after prompt assembly and again
  // after first usage-event reconciliation. Tier encodes the resolution path.
  context_breakdown: [
    "aggregateCostUsd",
    "apiReportedTotal",
    "cacheCreationTokens",
    "cacheReadTokens",
    "categories",
    "contextWindow",
    "model",
    "modelBreakdown",
    "occupancyTokens",
    "totalTokens",
    "unaccounted",
  ],
};

// ─── TS SharedTypes field map ───

export const TS_SHARED_TYPES: Record<string, string[]> = {
  ResourceItem: ["content", "conversationId", "createdAt", "id", "kind", "metadata", "producer", "read", "title", "updatedAt"],
  ResourceFilter: ["conversationId", "id", "kind", "limit", "producer", "since"],
  StatusFields: [
    "activeBackgroundTasks",
    "backgroundAgents",
    "backgroundShells",
    "hasPendingWork",
    "runEpoch",
    "contextPercent",
    "contextTokens",
    "contextEffectiveLimit",
    "contextWindow",
    "completionReason",
    "conversationCostUsd",
    "conversationTurns",
    "extensionName",
    "label",
    "model",
    "numTurns",
    "permissionDenials",
    "runCostUsd",
    "sessionId",
    "state",
    "team",
  ],
  SessionStatus: [
    "activeBackgroundTasks",
    "backgroundAgentCount",
    "backgroundShellCount",
    "hasPendingWork",
    "runEpoch",
    "contextPercent",
    "contextTokens",
    "contextEffectiveLimit",
    "contextWindow",
    "conversationCostUsd",
    "extensionName",
    "hasInflightRun",
    "key",
    "lastEmittedAt",
    "model",
    "permissionDenialsPending",
    "runCostUsd",
    "sessionId",
    "state",
    "stateSince",
  ],
  ModelTierEntry: ["fallbacks", "model", "name"],
  BackgroundTaskState: [
    "command",
    "notifyOnComplete",
    "startedAt",
    "taskId",
    "toolId",
  ],
  EngineConfig: [
    "claudeCompat",
    "clientWorkspaceContext",
    "extensions",
    "forceNewConversation",
    "maxTokens",
    "model",
    "parentConversationId",
    "pinned",
    "profileId",
    "projectDirectory",
    "runRecovery",
    "sessionId",
    "systemHint",
    "thinking",
    "toolGate",
    "workingDirectory",
    "workspaceWatchIgnore",
  ],
  MessageEndUsage: [
    "contextPercent",
    "cost",
    "entryId",
    "inputTokens",
    "outputTokens",
    "userEntryId",
  ],
  PermissionOpt: ["id", "kind", "label"],
  McpServerInfo: ["name", "status"],
  UsageData: [
    "cache_creation_input_tokens",
    "cache_read_input_tokens",
    "input_tokens",
    "output_tokens",
    "service_tier",
  ],
  AgentStateUpdate: ["id", "metadata", "name", "status"],
  ModelEntry: [
    "contextWindow",
    "effectiveContextLimit",
    "costPer1kInput",
    "costPer1kOutput",
    "costPerImage",
    "dialect",
    "id",
    "isCustom",
    "maxOutputTokens",
    "modelKind",
    "providerId",
    "supportsCaching",
    "supportsImages",
    "supportsThinking",
    "thinkingEfforts",
    "thinkingMode",
    "tokenizer",
  ],
  ProviderEntry: [
    "apiKeyRef",
    "authSource",
    "backend",
    "baseURL",
    "cli",
    "displayName",
    "hasAuth",
    "id",
  ],
  // Delegated-CLI install/auth status carried on ProviderEntry.cli. Mirrors
  // Go's ProviderCliStatus.
  ProviderCliStatus: [
    "authMethod",
    "authenticated",
    "backend",
    "binaryPath",
    "email",
    "installed",
    "label",
    "planType",
    "probedAt",
    "version",
  ],
  // Enterprise session/agent caps (D-007). Mirrors Go's ResourceLimits in
  // internal/types/config_resource_limits.go; carried inside the
  // get_enterprise_policy response blob.
  ResourceLimits: ["maxAgentsPerSession", "maxSessions"],
  // Extension allowlist entry (feature 0011 / D-020, issue #308). An element
  // of EnterpriseConfig.ExtensionAllowlist, carried inside the
  // get_enterprise_policy blob. sha256 is omitempty in Go — TS-optional matches.
  ExtensionAllowlistEntry: ["id", "sha256"],
  // Client-supplied workspace context. Mirrors Go's ClientWorkspaceContext.
  ClientWorkspaceContext: ["bench", "cwd", "data", "kind", "text"],
  // Client tool gate declaration (EngineConfig.toolGate). Mirrors Go's
  // ToolGateConfig in internal/types/tool_gate.go.
  ToolGateConfig: [
    "clientToolTimeoutMs",
    "clientTools",
    "enabled",
    "timeoutDecision",
    "timeoutMs",
    "tools",
  ],
  // One client-executed tool declaration (ToolGateConfig.clientTools).
  // humanWait routes the fulfillment to the engine's indefinite human-wait
  // path instead of the finite client-tool timeout.
  ClientToolDef: [
    "description",
    "humanWait",
    "inputSchema",
    "name",
    "planModeSafe",
  ],
  // One pending client-tool call carried on engine_client_tool_state
  // snapshots (complete replacement; [] is the authoritative clear).
  ClientToolCallState: [
    "cwd",
    "humanWait",
    "requestId",
    "runId",
    "startedAt",
    "toolInput",
    "toolName",
  ],
  // Payload of engine_provider_login (EngineEvent.providerLogin). Mirrors Go's
  // ProviderLoginUpdate.
  ProviderLoginUpdate: [
    "authUrl",
    "backend",
    "loginError",
    "loginId",
    "provider",
    "stage",
    "userCode",
    "verificationUrl",
  ],
  // One configured MCP server carried inside engine_mcp_servers snapshots.
  // connected and authenticated are independent by design — see the
  // McpServerStatus doc comment in types-engine-event.ts.
  McpServerStatus: [
    "authenticated",
    "command",
    "connected",
    "lastError",
    "name",
    "protocolVersion",
    "capabilities",
    "toolCount",
    "transport",
    "url",
  ],
  // Slash-command listing carried inside engine_command_registry snapshots.
  // The desktop's prompt pipeline reads this off the wire to populate a
  // routing-hint cache keyed by session — see desktop/src/main/prompt-pipeline.ts.
  EngineCommandListing: ["description", "name"],
  // Per-category token breakdown category row (one entry per category in
  // ContextBreakdownPayload.categories). Mirrors Go's ContextBreakdownCategory.
  ContextBreakdownCategory: ["kind", "name", "path", "tier", "tokens"],
  // Wire payload for engine_context_breakdown. Mirrors Go's ContextBreakdownPayload.
  ContextBreakdownPayload: [
    "aggregateCostUsd",
    "apiReportedTotal",
    "cacheCreationTokens",
    "cacheReadTokens",
    "categories",
    "contextWindow",
    "model",
    "modelBreakdown",
    "occupancyTokens",
    "totalTokens",
    "unaccounted",
  ],
  // Per-model cost breakdown row. Mirrors Go's ModelBreakdown in types/model_breakdown.go.
  ModelBreakdown: [
    "conversations",
    "costUsd",
    "inputTokens",
    "isSelf",
    "model",
    "outputTokens",
  ],
  // Go SessionMessage ↔ TS SessionLoadMessage (types-session.ts). The TS type
  // also carries `userExecuted`, a desktop-only concept intentionally
  // excluded from the contract.
  SessionMessage: [
    "attachments",
    "backgroundTaskId",
    "backgroundWork",
    "content",
    "id",
    "implementationPhase",
    "injectionKind",
    "internal",
    "isError",
    "machineAuthored",
    "markerClearedBlocks",
    "markerKind",
    "markerMachineAuthored",
    "markerMessageLength",
    "markerMessagesAfter",
    "markerMessagesBefore",
    "markerMicroOnly",
    "markerPlanFilePath",
    "markerPlanOperation",
    "markerPlanSlug",
    "markerStrategy",
    "markerSummary",
    "role",
    "slashArgs",
    "slashCommand",
    "slashFrontmatter",
    "slashModelAlias",
    "slashModelEffective",
    "slashSource",
    "timestamp",
    "toolId",
    "toolInput",
    "toolName",
  ],
  SessionMessageAttachment: [
    "contentHash",
    "id",
    "mimeType",
    "name",
    "path",
    "type",
  ],
  // Wire shape for content blocks carried inside LlmMessage payloads.
  // The compact_boundary variant (gentle-knitting-cup plan) added the
  // optional summary / trigger / messages* / clearedBlocks / tokensBefore
  // / factCount / recentFiles fields; the existing tool/image/text
  // variants share the same struct so every variant shows up here.
  LlmContentBlock: [
    "background_task_id",
    "clearedBlocks",
    "content",
    "contextPaths",
    "factCount",
    "id",
    "input",
    "is_error",
    "messagesAfter",
    "messagesBefore",
    "messagesSummarized",
    "name",
    "recentFiles",
    "restoredSkills",
    "skillInvokedAt",
    "skillName",
    "skillNames",
    "skillSource",
    "source",
    "summary",
    "text",
    "thinking",
    "tokensBefore",
    "tool_use_id",
    "trigger",
    "type",
  ],
};
