package telemetryformat

import (
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

// updateParityFixture regenerates assets/telemetry-frame-parity.json from this
// package, the Go decoder being the source of truth. Run:
//
//	cd engine && go test ./internal/telemetryformat/ -run TestFrameParityFixture -update
var updateParityFixture = flag.Bool("update", false, "rewrite the cross-language frame parity fixture")

// parityFixturePath is the shared fixture both decoders assert against. It sits
// at the repo root beside theme-parity.json, the existing cross-language
// fixture, because it belongs to neither surface alone.
const parityFixturePath = "../../../assets/telemetry-frame-parity.json"

type parityFixture struct {
	// Comment states the fixture's contract for whoever opens the file.
	Comment string `json:"_comment"`
	// FrameVersion the fixture was generated against. A decoder whose own
	// version is below this cannot satisfy the "above is rejected" cases.
	FrameVersion int          `json:"frame_version"`
	Expand       []parityCase `json:"expand"`
	Reject       []parityCase `json:"reject"`
}

type parityCase struct {
	Name string `json:"name"`
	Line string `json:"line"`
	// Expect is the expanded events, in order. Empty for a reject case.
	Expect []map[string]any `json:"expect,omitempty"`
}

// parityInputs are the frame lines both decoders must agree on. Inputs are
// hand-written (they are the contract); expectations are generated.
func parityInputs() ([]parityCase, []parityCase) {
	base := `{"record":"telemetry.frame","schema":4,` +
		`"identities":[{"component":"engine","install_id":"install-1","host":"host-1","version":"v1","user":"user@example.com"}],` +
		`"contexts":[{"context":{"session_id":"sess-1"},"trace_id":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}],` +
		`"events":[` +
		`{"i":0,"c":0,"name":"run.complete","ts":"2026-03-20T12:00:00Z","event_id":"e1","payload":{"cost_usd":0.5}},` +
		`{"i":0,"name":"tool.execute","ts":"2026-03-20T12:00:01Z","payload":{"tool":"Bash"}}]}`

	older := `{"record":"telemetry.frame","schema":3,` +
		`"identities":[{"component":"engine","install_id":"install-1","host":"host-1","version":"v1"}],` +
		`"contexts":[],` +
		`"events":[{"i":0,"name":"legacy.event","ts":"2026-03-20T12:00:00Z","payload":{"k":"v"}}]}`

	unknowns := `{"record":"telemetry.frame","schema":4,"future_table":[{"k":"v"}],` +
		`"identities":[{"component":"engine","install_id":"install-1","host":"host-1","version":"v1","future_identity_field":"x"}],` +
		`"contexts":[],` +
		`"events":[{"i":0,"name":"forward.compatible","ts":"2026-03-20T12:00:00Z","payload":{"k":"v"},"future_event_field":"x"}]}`

	expand := []parityCase{
		{Name: "interned identity and context shared by two events", Line: base},
		{Name: "frame below this reader's version still expands", Line: older},
		{Name: "unknown fields drop, known fields survive", Line: unknowns},
	}
	reject := []parityCase{
		{Name: "schema above this reader", Line: `{"record":"telemetry.frame","schema":9999,"identities":[{"component":"engine","install_id":"i","host":"h","version":"v"}],"contexts":[],"events":[{"i":0,"name":"n","ts":"t","payload":{}}]}`},
		{Name: "identity table index out of range", Line: `{"record":"telemetry.frame","schema":4,"identities":[],"contexts":[],"events":[{"i":7,"name":"n","ts":"t","payload":{}}]}`},
		{Name: "unsupported record discriminator", Line: `{"record":"telemetry.something-else","schema":4,"identities":[],"contexts":[],"events":[]}`},
	}
	return expand, reject
}

// TestFrameParityFixture asserts the Go decoder against the shared fixture, and
// regenerates it under -update. The desktop decoder asserts against the same
// file (desktop/src/main/__tests__/telemetry-frame-parity.test.ts), so a change
// to either implementation that is not mirrored in the other fails one of them.
func TestFrameParityFixture(t *testing.T) {
	expand, reject := parityInputs()

	if *updateParityFixture {
		for index := range expand {
			events, err := DecodeLine([]byte(expand[index].Line))
			if err != nil {
				t.Fatalf("%s: %v", expand[index].Name, err)
			}
			expand[index].Expect = eventsAsMaps(t, events)
		}
		fixture := parityFixture{
			Comment: "Generated by `cd engine && go test ./internal/telemetryformat/ -run TestFrameParityFixture -update`. " +
				"Asserted by both the Go and desktop frame decoders so neither can drift. Do not hand-edit.",
			FrameVersion: FrameVersion,
			Expand:       expand,
			Reject:       reject,
		}
		encoded, err := json.MarshalIndent(fixture, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Clean(parityFixturePath), append(encoded, '\n'), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", parityFixturePath)
		return
	}

	data, err := os.ReadFile(filepath.Clean(parityFixturePath))
	if err != nil {
		t.Fatalf("read fixture: %v (regenerate with -update)", err)
	}
	var fixture parityFixture
	if err := json.Unmarshal(data, &fixture); err != nil {
		t.Fatal(err)
	}
	if fixture.FrameVersion != FrameVersion {
		t.Fatalf("fixture frame_version = %d, this package is %d — regenerate with -update",
			fixture.FrameVersion, FrameVersion)
	}
	if len(fixture.Expand) != len(expand) || len(fixture.Reject) != len(reject) {
		t.Fatalf("fixture case counts drifted from parityInputs — regenerate with -update")
	}

	for _, testCase := range fixture.Expand {
		events, err := DecodeLine([]byte(testCase.Line))
		if err != nil {
			t.Errorf("%s: DecodeLine = %v, want it accepted", testCase.Name, err)
			continue
		}
		if got := eventsAsMaps(t, events); !reflect.DeepEqual(got, testCase.Expect) {
			t.Errorf("%s:\n got %v\nwant %v", testCase.Name, got, testCase.Expect)
		}
	}
	for _, testCase := range fixture.Reject {
		if _, err := DecodeLine([]byte(testCase.Line)); err == nil {
			t.Errorf("%s: DecodeLine accepted the line, want a rejection", testCase.Name)
		}
	}
}

// eventsAsMaps round-trips expanded events through JSON so the fixture records
// the wire shape a consumer sees, not the Go struct.
func eventsAsMaps(t *testing.T, events []Event) []map[string]any {
	t.Helper()
	out := make([]map[string]any, 0, len(events))
	for _, event := range events {
		encoded, err := json.Marshal(event)
		if err != nil {
			t.Fatal(err)
		}
		var asMap map[string]any
		if err := json.Unmarshal(encoded, &asMap); err != nil {
			t.Fatal(err)
		}
		out = append(out, asMap)
	}
	return out
}
