/** Main-process compatibility barrel for durable desktop automation types. */
export type {
  AutomationValue,
  AutomationTrigger,
  AutomationCondition,
  AutomationConditionExpression,
  AutomationConditionGroup,
  AutomationBranchStep,
  AutomationStep,
  AutomationAction,
  AutomationDefinition,
  AutomationEvent,
  AutomationCausation,
  AutomationConditionDecision,
  AutomationConditionDecisionResult,
  AutomationConditionDecisionTree,
  AutomationConditionGroupDecision,
  AutomationEvaluationTrace,
  AutomationStepDecision,
  AutomationHistoryEntry,
  AutomationDocument,
  EnterpriseAutomationPolicy,
  AutomationLayers,
  EffectiveAutomations,
  AutomationSource,
  AutomationSourceEntry,
  AutomationListing,
  AutomationActionContext,
  AutomationActionRunner,
  AutomationEvaluation,
} from "../../shared/types-automation";
