// @vitest-environment jsdom
/**
 * A re-attached terminal must not answer the questions in its own history.
 *
 * The attach history is the raw pty stream, so it carries every query a
 * program sent while it ran (a Go CLI using lipgloss asks for the background
 * color and the cursor position at startup). A real xterm answers them as it
 * parses; before the fix every re-attach wrote those answers into the live
 * shell, which showed them as `11;rgb:0000/0000/0000;1R` at the prompt.
 *
 * This uses the real xterm, not a stub: the answers are generated by xterm's
 * parser, so only the real one can show whether they reach the pty.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import React, { act } from 'react'
import { createRoot, type Root } from 'react-dom/client'

const { terminalAttach, terminalWrite, dataListeners } = vi.hoisted(() => ({
  terminalAttach: vi.fn(),
  terminalWrite: vi.fn(),
  dataListeners: [] as Array<(key: string, data: string) => void>,
}))

vi.mock('../../../host/host-instance', () => ({
  host: {
    shell: {
      terminalAttach,
      terminalWrite,
      terminalResize: vi.fn(),
      onTerminalData: (cb: (key: string, data: string) => void) => {
        dataListeners.push(cb)
        return () => undefined
      },
      onTerminalExit: () => () => undefined,
    },
    capabilities: () => ['terminal'],
  },
}))
vi.mock('../../../theme', () => ({ useColors: () => new Proxy({}, { get: () => '#000' }) }))
vi.mock('../../../preferences', () => ({
  usePreferencesStore: (selector: (s: { terminalFontFamily: string; terminalFontSize: number; uiZoom: number }) => unknown) =>
    selector({ terminalFontFamily: 'monospace', terminalFontSize: 12, uiZoom: 1 }),
}))
vi.mock('../../../rendererLogger', () => ({ rDebug: vi.fn(), rWarn: vi.fn() }))

;(globalThis as unknown as { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT = true

import { TerminalSurface } from './TerminalSurface'

// What `infra --version` (lipgloss via termenv) writes before its own output.
const STARTUP_QUERIES = '\x1b]11;?\x1b\\\x1b[6n'
const KEY = 'tab-1:surface:inst-1'

let container: HTMLDivElement
let root: Root

beforeEach(() => {
  terminalAttach.mockReset()
  terminalWrite.mockReset()
  dataListeners.length = 0
  container = document.createElement('div')
  document.body.appendChild(container)
  window.matchMedia ??= ((): MediaQueryList => ({
    matches: false,
    media: '',
    onchange: null,
    addListener: () => {},
    removeListener: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    dispatchEvent: () => false,
  })) as unknown as typeof window.matchMedia
})

afterEach(() => {
  act(() => root?.unmount())
  container.remove()
})

/** Let xterm's write queue (setTimeout-driven) parse everything written so far. */
async function settle(): Promise<void> {
  await act(async () => {
    await new Promise((resolve) => setTimeout(resolve, 50))
  })
}

function mount(): void {
  act(() => {
    root = createRoot(container)
    root.render(React.createElement(TerminalSurface, { tabId: 'tab-1', instanceId: 'inst-1', cwd: '/repo' }))
  })
}

function answersWritten(): string[] {
  return terminalWrite.mock.calls.filter(([key]) => key === KEY).map(([, data]) => data as string)
}

describe('TerminalSurface history answers', () => {
  it('does not answer queries replayed from the attach history', async () => {
    terminalAttach.mockResolvedValue({
      history: `$ infra --version\r\n${STARTUP_QUERIES}infra version 1\r\n$ `,
      running: true,
      exitCode: null,
      cwdFellBack: false,
      startError: null,
    })
    mount()
    await settle()

    expect(terminalAttach).toHaveBeenCalledTimes(1)
    expect(answersWritten()).toEqual([])
  })

  it('still answers a query that arrives live after the history', async () => {
    terminalAttach.mockResolvedValue({
      history: `${STARTUP_QUERIES}old output\r\n`,
      running: true,
      exitCode: null,
      cwdFellBack: false,
      startError: null,
    })
    mount()
    await settle()
    act(() => {
      for (const listener of dataListeners) listener(KEY, STARTUP_QUERIES)
    })
    await settle()

    // Exactly one answer pair: the live query's, none for the replayed one.
    const answers = answersWritten()
    expect(answers).toHaveLength(2)
    expect(answers[0]).toMatch(/^\x1b\]11;rgb:[0-9a-f/]+\x1b\\$/)
    expect(answers[1]).toMatch(/^\x1b\[\d+;\d+R$/)
  })
})
